# Generated by Django 4.2.4 on 2023-09-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_quizrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizrating',
            name='created_at',
        ),
    ]
