# Generated by Django 4.2.4 on 2023-09-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_remove_quizrating_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_options',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
