# Generated by Django 4.2.4 on 2023-09-03 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_question_num_options_quiz_num_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_options',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_questions',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
